name: Build Commit

on:
  push:
    paths:
      - ".github/workflows/build-commit.yml"
      - "src/**"
      - "*.sln"
  workflow_dispatch:

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: '0'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Test
        run: dotnet test --blame --blame-hang-timeout=30s
      - name: Package
        run: dotnet pack -c Release -o build -p:Nightly=$(printf "%0*d" 5 ${{ github.run_number }}) src/OoLunar.DSharpPlus.CommandAll.csproj
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DSharpPlus.CommandAll-Nightly-${{ github.run_number }}∕${{ github.run_attempt }}.zip
          path: ./build/*
      - name: Publish Nightly Nuget Packages
        run: |
          dotnet nuget push "build/*" --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
          echo LATEST_STABLE_VERSION=$(git describe --abbrev=0 --tags 2>/dev/null || echo '') >> $GITHUB_ENV
          dotnet run --project ./tools/AutoUpdateChannelDescription --framework=net8.0 -p:Nightly=$(printf "%0*d" 5 ${{ github.run_number }})
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_CHANNEL_TOPIC: ${{ secrets.DISCORD_CHANNEL_TOPIC }}
          NUGET_URL: ${{ secrets.NUGET_URL }}
          GITHUB_URL : ${{ github.server_url }}/${{ github.repository }}
