name: .NET Build

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: self-hosted
    if: "!contains(toJSON(github.event.commits.*.message), '[ci-skip]')"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: dotnet publish src/OoLunar.DSharpPlus.CommandAll.csproj -c Debug -f net7.0 --self-contained -p:DebugType=embedded
      - name: Test
        run: dotnet test --blame --blame-hang-timeout=30s
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'push' }}
        with:
          name: OoLunar.DSharpPlus.CommandAll-${{ github.run_number }}∕${{ github.run_attempt }}
          path: ./src/bin/Debug/net7.0/publish/