name: .NET Build

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build, Test, Post Nightly
    runs-on: self-hosted
    if: "!contains(toJSON(github.event.commits.*.message), '[ci-skip]')"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: '0'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
        env:
          DOTNET_INSTALL_DIR: ${{ github.workspace }}/.dotnet
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      - name: Test
        run: dotnet test --blame --blame-hang-timeout=30s
      - name: Package
        run: dotnet pack -c Debug -o build -p:Nightly=${{ github.run_number }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'push' }}
        with:
          name: OoLunar.DSharpPlus.CommandAll-Nightly-${{ github.run_number }}∕${{ github.run_attempt }}
          path: ./src/bin/Debug/net7.0/publish/
      - name: "Publish Nightly Nuget Packages"
        run: "dotnet nuget push \"build/*\" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json" # If the package version does not comply with SemVer, it will be set as a pre-release version automatically.
      - name: "Update Discord Channel Topic"
        run: "dotnet run --project ./tools/AutoUpdateChannelDescription -p:Nightly=${{ github.run_number }} -- $(git describe --abbrev=0 --tags)"
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_CHANNEL_TOPIC: ${{ secrets.DISCORD_CHANNEL_TOPIC }}
          NUGET_URL: ${{ secrets.NUGET_URL }}
          GITHUB_URL : ${{ github.server_url }}/${{ github.repository }}
