name: .NET Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Test
    runs-on: self-hosted
    if: "!contains(toJSON(github.event.commits.*.message), '[ci-skip]')"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Test
        run: dotnet test --blame --blame-hang-timeout=30s