name: Publish Release
on:
  release:
    types: ["published"]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  nuget-release:
    name: Nuget Release
    runs-on: self-hosted
    if: "!contains(toJSON(github.event.head_commit.message), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Build Nuget Packages
        run: mkdir build && dotnet pack -c Release -o build -p:Version=${{ github.event.release.tag_name }}
      - name: Publish Nuget Packages
        run: dotnet nuget push "build/*" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      - name: Upload Nuget Packages To Github Actions
        uses: actions/upload-artifact@v3
        with:
          name: OoLunar.DSharpPlus.CommandAll-${{ github.event.release.tag_name }}.zip
          path: build/*
      - name: Upload Nuget Packages To Github Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: build/*
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true # We don't want to update the body of the release.
          omitNameDuringUpdate: true # We don't want to update the name of the release.
