name: .NET Build

on:
  pull_request:

jobs:
  build-and-test:
    name: Build, Test, Post Nightly
    runs-on: self-hosted
    if: "!contains(toJSON(github.event.head_commit.message), '[ci-skip]')"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: '0'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
        env:
          DOTNET_INSTALL_DIR: ${{ github.workspace }}/../.dotnet
      - name: Test
        run: dotnet test --blame --blame-hang-timeout=30s
      - name: Package
        run: dotnet pack -c Debug -o build -p:Nightly=$(printf \"%0*d\n\" 5 ${{ github.run_number }})
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: OoLunar.DSharpPlus.CommandAll-Nightly-${{ github.run_number }}∕${{ github.run_attempt }}.zip
          path: ./src/bin/Debug/net7.0/publish/